version: '3.8'

services: 
  postgres:
    image: postgres:latest
    container_name: phoenix_postgres
    ports:
      - "5432:5432"
    volumes:
      - upraised_data:/var/lib/postgresql
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      
  redis: 
    image: redis:latest
    container_name: phoenix_redis
    ports:
      - 6379:6379
    restart: always
    
  phoenix_api:
    build: .
    image: phoenix_api
    container_name: phoenix_api
    depends_on:
      - redis
      - postgres
    ports:
      - 3000:3000
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=${REDIS_URL}
    restart: always


volumes:
  upraised_data: